name: Build and push DocsGPT Docker image for development

on:
  workflow_dispatch:
  push:
    branches:
      - arm-builds

jobs:
  deploy:
    if: github.repository == 'arc53/DocsGPT'
    strategy:
      matrix:
        include:
          - platform: linux/amd64
            runner: ubuntu-latest
          - platform: linux/arm64
            runner: ubuntu-22.04-arm64
    runs-on: ${{ matrix.runner }}
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        if: matrix.platform == 'linux/arm64'
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker images to docker.io and ghcr.io
        uses: docker/build-push-action@v6
        with:
          file: './application/Dockerfile'
          platforms: ${{ matrix.platform }}
          context: ./application
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/docsgpt:develop
            ghcr.io/${{ github.repository_owner }}/docsgpt:develop
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/docsgpt:develop
          cache-to: type=inline

